export const BUSINESS_TYPES = [
  { value: "llc", label: "LLC" },
  { value: "corporation", label: "Corporation" },
  { value: "partnership", label: "Partnership" },
  { value: "sole_proprietorship", label: "Sole Proprietorship" },
  { value: "investment_fund", label: "Investment Fund" },
  { value: "societies", label: "Societies" },
  { value: "trust", label: "Trust" },
  { value: "government", label: "Government" },
  { value: "dao", label: "DAO" },
] as const;

export const ACCOUNT_PURPOSES = [
  {
    value: "receive_payments_for_goods_and_services",
    label: "Receive Payments for Goods & Services",
  },
  { value: "pay_suppliers", label: "Pay Suppliers" },
  { value: "payroll", label: "Payroll" },
  { value: "treasury_management", label: "Treasury Management" },
  { value: "other", label: "Other" },
] as const;

export const SOURCE_OF_FUNDS = [
  { value: "business_loans", label: "Business Loans" },
  { value: "grants", label: "Grants" },
  { value: "inter_company_funds", label: "Inter-Company Funds" },
  { value: "investment_proceeds", label: "Investment Proceeds" },
  { value: "legal_settlement", label: "Legal Settlement" },
  { value: "owners_capital", label: "Owner's Capital" },
  { value: "pension_retirement", label: "Pension/Retirement" },
  { value: "sale_of_assets", label: "Sale of Assets" },
  {
    value: "sales_of_goods_and_services",
    label: "Sales of Goods & Services",
  },
  { value: "tax_refund", label: "Tax Refund" },
  { value: "third_party_funds", label: "Third Party Funds" },
  { value: "treasury_reserves", label: "Treasury Reserves" },
] as const;

export const SOURCE_OF_WEALTH = [
  {
    value: "business_dividends_or_profits",
    label: "Business Dividends or Profits",
  },
  { value: "investments", label: "Investments" },
  { value: "asset_sales", label: "Asset Sales" },
  {
    value: "client_investor_contributions",
    label: "Client/Investor Contributions",
  },
  { value: "gambling", label: "Gambling" },
  { value: "charitable_contributions", label: "Charitable Contributions" },
  { value: "inheritance", label: "Inheritance" },
  {
    value: "affiliate_or_royalty_income",
    label: "Affiliate or Royalty Income",
  },
] as const;

export const REVENUE_RANGES = [
  { value: "0_99999", label: "Under $100K" },
  { value: "100000_999999", label: "$100K - $1M" },
  { value: "1000000_9999999", label: "$1M - $10M" },
  { value: "10000000_49999999", label: "$10M - $50M" },
  { value: "50000000_249999999", label: "$50M - $250M" },
  { value: "2500000000_plus", label: "$2.5B+" },
] as const;

export const MONTHLY_VOLUME_RANGES = [
  { value: "0_99999", label: "Under $100K" },
  { value: "100000_999999", label: "$100K - $1M" },
  { value: "1000000_9999999", label: "$1M - $10M" },
  { value: "10000000_49999999", label: "$10M - $50M" },
  { value: "50000000_249999999", label: "$50M - $250M" },
  { value: "2500000000_plus", label: "$2.5B+" },
] as const;

export const TAX_TYPES = [
  { value: "SSN", label: "SSN" },
  { value: "EIN", label: "EIN" },
  { value: "TFN", label: "TFN" },
  { value: "ABN", label: "ABN" },
  { value: "ACN", label: "ACN" },
  { value: "UTR", label: "UTR" },
  { value: "NINO", label: "NINO" },
  { value: "NRIC", label: "NRIC" },
  { value: "FIN", label: "FIN" },
  { value: "ASDG", label: "ASDG" },
  { value: "ITR", label: "ITR" },
  { value: "NIF", label: "NIF" },
  { value: "TIN", label: "TIN" },
  { value: "VAT", label: "VAT" },
  { value: "CUIL", label: "CUIL" },
  { value: "CUIT", label: "CUIT" },
  { value: "DNI", label: "DNI" },
  { value: "BIN", label: "BIN" },
  { value: "UNP", label: "UNP" },
  { value: "RNPM", label: "RNPM" },
  { value: "NIT", label: "NIT" },
  { value: "CPF", label: "CPF" },
  { value: "CNPJ", label: "CNPJ" },
  { value: "NIRE", label: "NIRE" },
  { value: "UCN", label: "UCN" },
  { value: "UIC", label: "UIC" },
  { value: "SIN", label: "SIN" },
  { value: "BN", label: "BN" },
  { value: "RUT", label: "RUT" },
  { value: "IIN", label: "IIN" },
  { value: "USCC", label: "USCC" },
  { value: "CNOC", label: "CNOC" },
  { value: "USCN", label: "USCN" },
  { value: "ITIN", label: "ITIN" },
  { value: "CPJ", label: "CPJ" },
  { value: "OIB", label: "OIB" },
  { value: "DIC", label: "DIC" },
  { value: "CPR", label: "CPR" },
  { value: "CVR", label: "CVR" },
  { value: "CN", label: "CN" },
  { value: "RNC", label: "RNC" },
  { value: "RUC", label: "RUC" },
  { value: "TN", label: "TN" },
  { value: "HETU", label: "HETU" },
  { value: "YT", label: "YT" },
  { value: "ALV", label: "ALV" },
  { value: "SIREN", label: "SIREN" },
  { value: "IDNR", label: "IDNR" },
  { value: "STNR", label: "STNR" },
  { value: "VTA", label: "VTA" },
  { value: "HKID", label: "HKID" },
  { value: "AJ", label: "AJ" },
  { value: "EN", label: "EN" },
  { value: "KN", label: "KN" },
  { value: "VSK", label: "VSK" },
  { value: "PAN", label: "PAN" },
  { value: "GSTN", label: "GSTN" },
  { value: "NIK", label: "NIK" },
  { value: "NPWP", label: "NPWP" },
  { value: "PPS", label: "PPS" },
  { value: "TRN", label: "TRN" },
  { value: "CRO", label: "CRO" },
  { value: "CHY", label: "CHY" },
  { value: "CF", label: "CF" },
  { value: "IVA", label: "IVA" },
  { value: "IN", label: "IN" },
  { value: "JCT", label: "JCT" },
  { value: "EDRPOU", label: "EDRPOU" },
  { value: "EID", label: "EID" },
] as const;

export const ID_TYPES = [
  { value: "drivers_license", label: "Driver's License" },
  { value: "passport", label: "Passport" },
  { value: "national_id", label: "National ID" },
  { value: "permanent_residency_id", label: "Permanent Residency ID" },
  { value: "other", label: "Other" },
] as const;

export const DOCUMENT_TYPES = [
  { value: "aml_comfort_letter", label: "AML Comfort Letter" },
  { value: "constitutional_document", label: "Constitutional Document" },
  { value: "directors_registry", label: "Directors Registry" },
  { value: "cert_of_incumbency", label: "Certificate of Incumbency" },
  {
    value: "e_signature_certificate",
    label: "E-Signature Certificate",
  },
  { value: "evidence_of_good_standing", label: "Evidence of Good Standing" },
  { value: "flow_of_funds", label: "Flow of Funds" },
  { value: "formation_document", label: "Formation Document" },
  { value: "marketing_materials", label: "Marketing Materials" },
  { value: "other", label: "Other" },
  { value: "ownership_chart", label: "Ownership Chart" },
  { value: "ownership_information", label: "Ownership Information" },
  { value: "proof_of_account_purpose", label: "Proof of Account Purpose" },
  { value: "proof_of_address", label: "Proof of Address" },
  {
    value: "proof_of_entity_name_change",
    label: "Proof of Entity Name Change",
  },
  {
    value: "proof_of_nature_of_business",
    label: "Proof of Nature of Business",
  },
  {
    value: "proof_of_nature_of_business_license",
    label: "Proof of Nature of Business License",
  },
  {
    value: "proof_of_nature_of_business_aml_policy",
    label: "Proof of Nature of Business AML Policy",
  },
  {
    value: "proof_of_signatory_authority",
    label: "Proof of Signatory Authority",
  },
  { value: "proof_of_source_of_funds", label: "Proof of Source of Funds" },
  {
    value: "proof_of_source_of_wealth",
    label: "Proof of Source of Wealth",
  },
  {
    value: "proof_of_tax_identification",
    label: "Proof of Tax Identification",
  },
  { value: "registration_document", label: "Registration Document" },
  { value: "shareholder_register", label: "Shareholder Register" },
  {
    value: "evidence_of_directors_and_controllers",
    label: "Evidence of Directors & Controllers",
  },
  {
    value: "tax_exempt_entity_confirmation",
    label: "Tax Exempt Entity Confirmation",
  },
] as const;

export const COUNTRIES = [
  { value: "USA", label: "United States" },
  { value: "CAN", label: "Canada" },
  { value: "GBR", label: "United Kingdom" },
  { value: "DEU", label: "Germany" },
  { value: "FRA", label: "France" },
  { value: "AUS", label: "Australia" },
  { value: "IND", label: "India" },
  { value: "SGP", label: "Singapore" },
  { value: "HKG", label: "Hong Kong" },
  { value: "JPN", label: "Japan" },
  { value: "BRA", label: "Brazil" },
  { value: "MEX", label: "Mexico" },
] as const;

export const US_STATES = [
  { value: "AL", label: "Alabama" },
  { value: "AK", label: "Alaska" },
  { value: "AZ", label: "Arizona" },
  { value: "AR", label: "Arkansas" },
  { value: "CA", label: "California" },
  { value: "CO", label: "Colorado" },
  { value: "CT", label: "Connecticut" },
  { value: "DE", label: "Delaware" },
  { value: "FL", label: "Florida" },
  { value: "GA", label: "Georgia" },
  { value: "HI", label: "Hawaii" },
  { value: "ID", label: "Idaho" },
  { value: "IL", label: "Illinois" },
  { value: "IN", label: "Indiana" },
  { value: "IA", label: "Iowa" },
  { value: "KS", label: "Kansas" },
  { value: "KY", label: "Kentucky" },
  { value: "LA", label: "Louisiana" },
  { value: "ME", label: "Maine" },
  { value: "MD", label: "Maryland" },
  { value: "MA", label: "Massachusetts" },
  { value: "MI", label: "Michigan" },
  { value: "MN", label: "Minnesota" },
  { value: "MS", label: "Mississippi" },
  { value: "MO", label: "Missouri" },
  { value: "MT", label: "Montana" },
  { value: "NE", label: "Nebraska" },
  { value: "NV", label: "Nevada" },
  { value: "NH", label: "New Hampshire" },
  { value: "NJ", label: "New Jersey" },
  { value: "NM", label: "New Mexico" },
  { value: "NY", label: "New York" },
  { value: "NC", label: "North Carolina" },
  { value: "ND", label: "North Dakota" },
  { value: "OH", label: "Ohio" },
  { value: "OK", label: "Oklahoma" },
  { value: "OR", label: "Oregon" },
  { value: "PA", label: "Pennsylvania" },
  { value: "RI", label: "Rhode Island" },
  { value: "SC", label: "South Carolina" },
  { value: "SD", label: "South Dakota" },
  { value: "TN", label: "Tennessee" },
  { value: "TX", label: "Texas" },
  { value: "UT", label: "Utah" },
  { value: "VT", label: "Vermont" },
  { value: "VA", label: "Virginia" },
  { value: "WA", label: "Washington" },
  { value: "WV", label: "West Virginia" },
  { value: "WI", label: "Wisconsin" },
  { value: "WY", label: "Wyoming" },
  { value: "DC", label: "District of Columbia" },
] as const;

export const ONBOARDING_STEPS = [
  { id: "business-details" as const, label: "Business Details", step: 1 },
  { id: "address-details" as const, label: "Address Details", step: 2 },
  { id: "tos" as const, label: "Terms of Service", step: 3 },
] as const;

export const DEFAULT_IDENTIFYING_INFO = {
  type: "",
  issuing_country: "",
  national_identity_number: "",
  image_front: "",
  image_back: "",
};

export const DEFAULT_PERSON = {
  first_name: "",
  middle_name: "",
  last_name: "",
  email: "",
  birth_date: "",
  primary_nationality: "",
  has_ownership: false,
  has_control: false,
  is_signer: false,
  is_director: false,
  ownership_percentage: 0,
  country_of_tax: "",
  tax_type: "",
  tax_id: "",
  identifying_information: [{ ...DEFAULT_IDENTIFYING_INFO }],
  poa: "",
  poa_type: "",
};
